Repository CEED/Laghos, pull requests merged in 2018-11, with the labels that each got.

#28 Adding README.md files in the directories for different versions.
  CHANGELOG
  README.md
  cuda/README.md
  cuda/laghos.cpp
  raja/README.md
  serial/README.md
  serial/laghos_s.cpp
  serial/makefile
Labels: enhancement

#33 Valgrind uninitialised warning fix
  laghos_solver.cpp
Labels: bug, minor

#36 Ability to do PA when velocity is in Bernstein.
  CHANGELOG
  laghos_assembly.cpp
  laghos_assembly.hpp
  laghos_solver.cpp
  serial/laghos_solver.cpp
Labels: enhancement

#32 AMR version the 'amr' subdirectory [amr-in-master]
  amr/README.md
  amr/data/sedov-amr-2422.png
  amr/data/sedov-amr-900.png
  amr/laghos.cpp
  amr/laghos_assembly.cpp
  amr/laghos_assembly.hpp
  amr/laghos_solver.cpp
  amr/laghos_solver.hpp
  amr/makefile
  data/sedov.png
Labels: enhancement

#38 Option to activate visc terms for smooth problems.
  README.md
  laghos.cpp
  serial/laghos.cpp
Labels: minor

#34 [OCCA] Added initial OCCA 1.0 port
  occa/.gitignore
  occa/README.md
  occa/config.json
  occa/kernels/cpu/force.okl
  occa/kernels/cpu/quadratureData.okl
  occa/kernels/force.okl
  occa/kernels/gpu/force.okl
  occa/kernels/gpu/quadratureData.okl
  occa/kernels/quadratureData.okl
  occa/laghos.cpp
  occa/laghos_assembly.cpp
  occa/laghos_assembly.hpp
  occa/laghos_solver.cpp
  occa/laghos_solver.hpp
  occa/laghos_utils.hpp
  occa/makefile
  occa/mpi_utils.hpp
Labels: enhancement

#40 Final changes for v2.0 release
  CHANGELOG
  README.md
  cuda/README.md
  raja/README.md
  serial/README.md
Labels: enhancement, minor

#39 Adding Travis CI testing
  .travis.yml
  CHANGELOG
Labels: building, enhancement
