Repository CEED/Laghos, pull requests merged in 2019-10, with the labels that each got.

#41 General blast position
  amr/laghos.cpp
  laghos.cpp
  laghos_solver.cpp
Labels: enhancement

#49 Touch .travis.yml
  .travis.yml
Labels: building, minor

#46 only include header if using openmpi
  cuda/cuda/config/config.cpp
Labels: building, minor

#50 README travis button
  README.md
Labels: building, enhancement, minor
