Repository CEED/Laghos, pull requests merged in 2020-12, with the labels that each got.

#93 Fix FA + triangles.
  data/square01_quad_unstr.mesh
  data/square01_tri.mesh
  laghos_solver.cpp
  laghos_solver.hpp
Labels: bug

#118 Add Rayleigh-Taylor Instability Problem
  README.md
  data/rt2D.mesh
  laghos.cpp
  laghos_assembly.hpp
  laghos_solver.cpp
  laghos_solver.hpp
  makefile
Labels: enhancement

#116 Rom absolute tests
  rom/laghos.cpp
  rom/makefile
  rom/tests/PrintParGridFunction.txt
  rom/tests/PrintParGridFunctionCall.txt
  rom/tests/REGRESSIONTEST.md
  rom/tests/basisComparator.cpp
  rom/tests/checkError.cpp
  rom/tests/computeSpeedup.cpp
  rom/tests/fileComparator.cpp
  rom/tests/gresho-vortices/absolute-gresho-vortices-time-window.csv
  rom/tests/gresho-vortices/absolute-gresho-vortices-time-window.sh
  rom/tests/runRegressionTests.sh
  rom/tests/sedov-blast/absolute-sedov-blast-time-window.csv
  rom/tests/sedov-blast/absolute-sedov-blast-time-window.sh
  rom/tests/sedov-blast/sedov-blast-parameter-variation.sh
  rom/tests/sedov-blast/sedov-blast-time-window-rhsbasis-parameter-variation-initial.sh
  rom/tests/sedov-blast/sedov-blast-time-window-rhsbasis-parameter-variation-interpolate.sh
  rom/tests/sedov-blast/sedov-blast-time-window-rhsbasis-parameter-variation-numsamp.sh
  rom/tests/sedov-blast/sedov-blast-time-window-rhsbasis-parameter-variation-previous.sh
  rom/tests/solutionComparator.cpp
  rom/tests/taylor-green/absolute-taylor-green.sh
  rom/tests/triple-point/absolute-triple-point.sh
Labels: RFR

#119 Update ROM to work with refactored libROM
  rom/laghos_rom.cpp
  rom/laghos_rom.hpp
  rom/laghos_utils.cpp
  rom/laghos_utils.hpp
  rom/merge.cpp
  rom/tests/REGRESSIONTEST.md
  rom/tests/runRegressionTests.sh
Labels: RFR
